### ISSUE TITLE
Build failed: You have to use a classifier to attach supplemental artifacts to the project instead of replacing them.

### ISSUE THREAD

**Issue by kerwin-zk** [oap-project/gluten#466] opened 2022-10-25 08:02 UTC
**Describe the bug**
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-jar-plugin:3.2.0:jar (default) on project spark-sql-columnar-shims-common: You have to use a classifier to attach supplemental artifacts to the project instead of replacing them.

**To Reproduce**
mvn clean package -Pbackends-velox -Pfull-scala-compiler -DskipTests -Dcheckstyle.skip -Dbuild_cpp=ON -Dbuild_velox=ON -Dbuild_velox_from_source=ON -Dbuild_arrow=ON

**Comment by jinchengchenghh** [comment] 2022-10-26 07:49
You can add -Pspark-3.2 to your compile command, it can work.
But your fix can enable profile spark-3.2 default without specify spark profile which is initial propose.
Thanks for your contribution!
I will merge it until CH backend test pass.

**Comment by FelixYBW** [comment] 2022-10-27 18:06
let's close it since it's fixed.

**Closed by FelixYBW** 2022-10-27 18:06 UTC
Labels: bug

**Comment by jinchengchenghh** [comment] 2022-10-28 02:11
Merged

**Comment by zhztheplayer** [comment] 2022-10-28 16:02
Reopened this since the changes has been reverted. See more details: https://github.com/oap-project/gluten/pull/477#issuecomment-1295169950

**Comment by jinchengchenghh** [comment] 2022-10-31 01:12
And this patch will cause Spark33 TPCDS q69 empty result. https://github.com/oap-project/gluten/pull/456
Reproduce:
```
git clone https://github.com/zhztheplayer/gluten-it.git
mvn clean package -Darrow.version=10.0.0-SNAPSHOT -Pspark-3.3 -Pgluten-velox
java -Xmx5G -cp target/gluten-it-1.0-SNAPSHOT-jar-with-dependencies.jar io.glutenproject.integration.tpc.Tpc --backend-type=velox --benchmark-type=ds --fixed-width-as-double --off-heap-size=2g -s=0.1 --cpus=4 --iterations=1 --log-level=2 --queries=q69
```
