### ISSUE TITLE
[VL] The latest code is very slow when reading HDFS data

### ISSUE THREAD

**Issue by liujiayi771** [oap-project/gluten#3718] opened 2023-11-15 06:38 UTC
### Backend

VL (Velox)

### Bug description

We test the latest code in TPCDS 1T in the same cluster and same configurations. Some queries like q74 q75 become very slow.
<img width="1122" alt="image" src="https://github.com/oap-project/gluten/assets/13622031/df0e9519-4780-4d5f-852f-6adf1c733e68">

### Spark version

Spark-3.3.x

**Comment by rui-mo** [comment] 2023-11-15 06:39
cc @zhouyuan

**Comment by rui-mo** [comment] 2023-11-15 06:40
The test is based on 5dabb5b66bd180cfc541c3ab652a863630481608.

**Comment by zhouyuan** [comment] 2023-11-15 07:01
Hi @liujiayi771 thanks for reporting, the notable changes on HDFS connector is https://github.com/facebookincubator/velox/pull/6140 which should improve the performance when reading.
Based on your description, it seems this only affects on some queries, so could this due to some special filter push down? 

I just checked TPCDS Q9 on our local cluster, it seems the performance on scan is not impacted a lot.  see below capture on new velox vs. old velox 
 
![Screenshot 2023-11-15 145418](https://github.com/oap-project/gluten/assets/43917/9b4000d5-2866-4d64-8d45-afbb73b3d981)

thanks, -yuan

**Comment by zhouyuan** [comment] 2023-11-15 07:02
@liujiayi771 btw, it seems the "total time scan total" on your new velox is "0ms", this seems not correct. 

-yuan

**Comment by liujiayi771** [comment] 2023-11-15 07:05
> Based on your description, it seems this only affects on some queries, so could this due to some special filter push down?
> 
> I just checked TPCDS Q9 on our local cluster, it seems the performance on scan is not impacted a lot. see below capture on new velox vs. old velox

@rui-mo checked the metrics code in gluten, it has some problems.

**Comment by liujiayi771** [comment] 2023-11-15 07:07
@zhouyuan Not only these queries, but many others have become slow as well. I have shared the test results with @rui-mo . Additionally, there is another scenario where if only queries 72-75 are executed, the execution time is normal. However, when running continuously from q1 to q75, it becomes very slow, indicating a possible memory leak issue.

**Comment by zhouyuan** [comment] 2023-11-15 08:01
@liujiayi771 agree based on your description. We ran into a similar issue(https://github.com/oap-project/gluten/pull/3483) before. Page cache become smaller on power test if huge page based allocation is enabled, thus table scan and shuffle read performance is impacted a lot for later queries. If convenient you may collect system level profiling data(page cache, memory footprint, on-heap, off-heap) to check.

-yuan

**Comment by liujiayi771** [comment] 2023-11-15 14:02
@zhouyuan @rui-mo After reverting https://github.com/facebookincubator/velox/pull/6140, the speed of reading from HDFS has been restored.

**Comment by liujiayi771** [comment] 2023-11-15 14:20
cc @waitinfuture

**Comment by zhouyuan** [comment] 2023-11-16 01:25
@liujiayi771 good to know, so it looks like the RCA is this patch has memory leakage?

I checked one of our stress test(repeat run of TPCDS Q95) with HDFS as the storage, looks like the memory usage is stable.
![image](https://github.com/oap-project/gluten/assets/43917/e4be7025-6663-4553-b999-e984dbe2de81)

thanks, -yuan

**Comment by Yohahaha** [comment] 2023-11-16 02:00
This issue not due to memory leak, 6140 will open HdfsReadFile on first use and close it on dtor, it cause problem when Velox cache lots of file handle (20,000), maybe partitioned dataset could reproduce this issue.

Two solutions here:
1. revert part of 6140, open then close hdfs file in pread. I doubt that open then close does not introduce performance issue as 6140 claimed.
2. pass file handle cache size config with a small value in Gluten.

**Comment by Yohahaha** [comment] 2023-11-16 02:38
> the performance benefit of #6140 is huge in local tests. maybe related with some specific configurations or some new libhdfs client impl.

We dont see performance gain, but this reason make sense for me. Let's fix it with solution 2 for now.

**Comment by liujiayi771** [comment] 2023-11-18 00:22
Fixed by disable file cache. https://github.com/oap-project/gluten/pull/3753

**Closed** 2023-11-18 00:22 UTC
Labels: bug, performance

**Comment by zhouyuan** [comment] 2023-11-18 02:47
Thank you for reporting and the quick fix!

-yuan
________________________________
