### ISSUE TITLE
[VL] Decimal TPCDS 1T in CentOS8 failures

### ISSUE THREAD

**Issue by liujiayi771** [oap-project/gluten#1263] opened 2023-03-31 08:51 UTC
When I tested 1 tb TPCDS on CentOS8 (actually Alinux3 based on CentOS8), I encountered some failure cases. I will try to find out the reason for the error and record it here.

- [x] ~~Q4 - sometimes core dump~~
- [x] ~~Q14a - plus overflow~~
- [ ] Q39a - the last 2 decimal places of some results are inconsistent
- [ ] Q39b - same as Q39a
- [x] ~~Q54 - the result is wrong, only one row is returned~~
- [x] ~~Q60 - Decimal precision 28 exceeds max precision~~
- [ ] Q66 - same as Q39a

**Comment by zhouyuan** [comment] 2023-03-31 10:24
@liujiayi771 thanks for reporting, the issues seems related with Cent8 as our ubuntu20.04 based TPCDS tests are fine. Will try to reproduce the issues here. 

-yuan

**Comment by JkSelf** [comment] 2023-04-03 01:46
@liujiayi771 Are the tests you do here tested with the latest code? We now have some bug fixes for decimal.

**Comment by rui-mo** [comment] 2023-04-03 03:31
@liujiayi771 Previously we could reproduce the issue of `Q4 - sometimes core dump`, but after Velox upgrading this time, q4 always succeeds in my testing. I guess it could be fixed by Velox upstream. Would you like to try the latest oap Velox and Gluten again?

**Comment by liujiayi771** [comment] 2023-04-05 12:19
> @liujiayi771 Are the tests you do here tested with the latest code? We now have some bug fixes for decimal.

I will try the latest code. I have also fix some bugs in sum.

**Comment by liujiayi771** [comment] 2023-04-05 12:29
> @liujiayi771 Previously we could reproduce the issue of `Q4 - sometimes core dump`, but after Velox upgrading this time, q4 always succeeds in my testing. I guess it could be fixed by Velox upstream. Would you like to try the latest oap Velox and Gluten again?
> 
> cc @zhouyuan @JkSelf

I'm sorry I just saw the message. I have tested q4 many times and there is no core dump.

**Comment by liujiayi771** [comment] 2023-04-05 23:45
14a and 60 can also pass now.

**Comment by zhouyuan** [comment] 2023-04-06 00:06
@liujiayi771 thanks for updating, the issues on Q39a/b are due to double precision issue if I recall correctly. The results will become stable if we use decimal type in the result schema

Thanks, -yuan

**Comment by liujiayi771** [comment] 2023-04-06 01:07
E0406 09:02:31.702051 1529800 Exceptions.h:68] Line: ../../velox/expression/CastExpr.cpp:275, Function:operator(), Expression:  Failed to cast from DECIMAL(21,6) to INTEGER: 9067.875600. , Source: RUNTIME, ErrorCode: INVALID_STATE.

I find above error when run query 54, can someone take a look? 
@JkSelf @rui-mo

**Comment by liujiayi771** [comment] 2023-04-06 02:16
In the latest code, "Decimal cast to integer error" in q54 also fixed. @JkSelf @rui-mo

**Comment by zhouyuan** [comment] 2023-04-06 02:25
Q66 related: https://github.com/oap-project/gluten/issues/1277

**Comment by zhouyuan** [comment] 2023-06-20 03:54
should be fixed in main branch

**Closed by zhouyuan** 2023-06-20 03:54 UTC
Labels: bug
