### ISSUE TITLE
TPC-DS q72 failed cause more than one key

### ISSUE THREAD

**Issue by Yohahaha** [oap-project/gluten#1141] opened 2023-03-15 13:19 UTC
**Describe the bug**
TPC- DS q72 throw exceptions
```
Caused by: java.lang.IllegalStateException: More than one key d_date_sk#166 found from build side relation output: List(d_date_sk#92, d_date#94, d_week_seq#96, d_date_sk#166)
	at org.apache.spark.sql.execution.GlutenBuildSideRelation.$anonfun$transform$1(GlutenBuildSideRelation.scala:100)
```

**Comment by zhouyuan** [comment] 2023-03-17 02:37
@Yohahaha 

The issue is due to "keys with same name" is marked as unsupported when building hash map. I also run into this issue on Q72 + CBO enabled. 

Can you please help to have a check if below quick patch could work? In my testing env it works.
 
```
diff --git a/gluten-data/src/main/scala/org/apache/spark/sql/execution/GlutenBuildSideRelation.scala b/gluten-data/src/main/scala/org/apache/spark/sql/execution/GlutenBuildSideRelation.scala
index 40ea5b95..f926a0d1 100644
--- a/gluten-data/src/main/scala/org/apache/spark/sql/execution/GlutenBuildSideRelation.scala
+++ b/gluten-data/src/main/scala/org/apache/spark/sql/execution/GlutenBuildSideRelation.scala
@@ -89,7 +89,7 @@ case class GlutenBuildSideRelation(mode: BroadcastMode,

         val columnInOutput = output.zipWithIndex.filter {
           p: (Attribute, Int) =>
-            p._1.name == columnExpr.name
+            p._1.name == columnExpr.name && p._1.exprId == columnExpr.exprId
         }
         if (columnInOutput.isEmpty) {
           throw new IllegalStateException(

```

-yuan

**Comment by Yohahaha** [comment] 2023-03-17 03:14
@zhouyuan 

It works.

I think use `exprId` and `name` to check `AttributeReference`'s equality is better, why we dont use this way or apply this patch for now?

**Comment by jinchengchenghh** [comment] 2023-04-04 09:22
Can we apply this patch? @zhouyuan

**Comment by FelixYBW** [comment] 2023-04-04 21:41
> Can we apply this patch? @zhouyuan

Is this fixed? If not who can submit the PR？

**Comment by zhouyuan** [comment] 2023-04-06 00:08
@jinchengchenghh  The patch is a quick fix and it seems introducing more bugs on other cases.  Created a pull request(#1288 ) on fixing these issues 

-yuan

**Comment by jinchengchenghh** [comment] 2023-04-06 00:47
It has passed CI. Does it have some hidden bugs?

**Comment by zhouyuan** [comment] 2023-04-06 02:24
@jinchengchenghh 

On my local setup, TPCDS Q5 failed due to below issue, looking on better fix on this. Not sure why CI does not ran into this issue though.  
```
Caused by: java.lang.IllegalStateException: Key d_date_sk#7977 not found from build side relation output: List(d_date_sk#7837)
        at org.apache.spark.sql.execution.GlutenBuildSideRelation.$anonfun$transform$1(GlutenBuildSideRelation.scala:96)
        at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:486)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:492)
        at scala.collection.Iterator.foreach(Iterator.scala:943)
        at scala.collection.Iterator.foreach$(Iterator.scala:943)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
        at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:62)
        at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
```
-yuan

**Comment by zhli1142015** [comment] 2023-04-17 04:30
> @jinchengchenghh
> 
> On my local setup, TPCDS Q5 failed due to below issue, looking on better fix on this. Not sure why CI does not ran into this issue though.
> 
> ```
> Caused by: java.lang.IllegalStateException: Key d_date_sk#7977 not found from build side relation output: List(d_date_sk#7837)
>         at org.apache.spark.sql.execution.GlutenBuildSideRelation.$anonfun$transform$1(GlutenBuildSideRelation.scala:96)
>         at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:486)
>         at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:492)
>         at scala.collection.Iterator.foreach(Iterator.scala:943)
>         at scala.collection.Iterator.foreach$(Iterator.scala:943)
>         at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
>         at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:62)
>         at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
> ```
> 
> -yuan

Hello @zhouyuan 
If only `columnInOutput.size > 1`, then we check the equality of exprId, this solves both the above issues in our TPCDS tests, hope this helps ~

**Comment by zhouyuan** [comment] 2023-04-17 05:15
> > @jinchengchenghh
> > On my local setup, TPCDS Q5 failed due to below issue, looking on better fix on this. Not sure why CI does not ran into this issue though.
> > ```
> > Caused by: java.lang.IllegalStateException: Key d_date_sk#7977 not found from build side relation output: List(d_date_sk#7837)
> >         at org.apache.spark.sql.execution.GlutenBuildSideRelation.$anonfun$transform$1(GlutenBuildSideRelation.scala:96)
> >         at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:486)
> >         at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:492)
> >         at scala.collection.Iterator.foreach(Iterator.scala:943)
> >         at scala.collection.Iterator.foreach$(Iterator.scala:943)
> >         at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
> >         at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:62)
> >         at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > -yuan
> 
> Hello @zhouyuan If only `columnInOutput.size > 1`, then we check the equality of exprId, this solves both the above issues in our TPCDS tests, hope this helps ~

@zhli1142015 thanks for the inputs, I actually made a patch here with this logic: https://github.com/oap-project/gluten/pull/1288
- on Q72 the issue is due to the output of build relation has two columns with same name but different exprId
- on Q5 the issue is due to a reused broadcast xchg, although there's only output column, the expr name and Id are not matching from the original plan

-yuan
-yuan

**Closed** 2023-04-17 10:20 UTC
Labels: bug
