### ISSUE TITLE
[CH] Array join tries to allocate too much memory leading to fail

### ISSUE THREAD

**Issue by zhanglistar** [oap-project/gluten#3136] opened 2023-09-13 09:41 UTC
### Backend

CH (ClickHouse)

### Bug description
d_3750_0.sql
Log:
```
23/09/13 17:27:55.564 ERROR [Executor task launch worker for task 30.0 in stage 0.0 (TID 47)] Executor: Exception in task 30.0 in stage 0.0 (TID 47)
io.glutenproject.exception.GlutenException: Allocator: Cannot mmap 64.00 GiB., errno: 12, strerror: Cannot allocate memory: while executing 'ARRAY JOIN assumeNotNull(tupleElement(arrayJoin(online),5_11)) :: 2 -> arrayJoin(assumeNotNull(tupleElement(arrayJoin(online),5_11))) Nullable(String) : 3'
0. ? @ 0x0000000014046b79 in /data5/hadoop/yarn/local/usercache/zhangzhibiao/filecache/298/libch.so
1. ? @ 0x000000000be96a57 in /data5/hadoop/yarn/local/usercache/zhangzhibiao/filecache/298/libch.so
2. ? @ 0x000000000be9b954 in /data5/hadoop/yarn/local/usercache/zhangzhibiao/filecache/298/libch.so
3. ? @ 0x000000000be978a8 in /data5/hadoop/yarn/local/usercache/zhangzhibiao/filecache/298/libch.so
4. ? @ 0x000000000be6a011 in /data5/hadoop/yarn/local/usercache/zhangzhibiao/filecache/298/libch.so
5. ? @ 0x000000000be69c1e in /data5/hadoop/yarn/local/usercache/zhangzhibiao/filecache/298/libch.so
6. ? @ 0x0000000010c3d396 in /data5/hadoop/yarn/local/usercache/zhangzhibiao/filecache/298/libch.so
7. ? @ 0x0000000010c3d124 in /data5/hadoop/yarn/local/usercache/zhangzhibiao/filecache/298/libch.so
8. ? @ 0x0000000010c3dfd9 in /data5/hadoop/yarn/local/usercache/zhangzhibiao/filecache/298/libch.so
9. ? @ 0x0000000010c3d190 in /data5/hadoop/yarn/local/usercache/zhangzhibiao/filecache/298/libch.so
10. ? @ 0x0000000010d33b24 in /data5/hadoop/yarn/local/usercache/zhangzhibiao/filecache/298/libch.so
11. ? @ 0x0000000010d741ef in /data5/hadoop/yarn/local/usercache/zhangzhibiao/filecache/298/libch.so
12. ? @ 0x0000000010d33b24 in /data5/hadoop/yarn/local/usercache/zhangzhibiao/filecache/298/libch.so
13. ? @ 0x00000000104c9df9 in /data5/hadoop/yarn/local/usercache/zhangzhibiao/filecache/298/libch.so
14. ? @ 0x0000000011722ad3 in /data5/hadoop/yarn/local/usercache/zhangzhibiao/filecache/298/libch.so
15. ? @ 0x00000000115c7ed0 in /data5/hadoop/yarn/local/usercache/zhangzhibiao/filecache/298/libch.so
16. ? @ 0x000000001162b90c in /data5/hadoop/yarn/local/usercache/zhangzhibiao/filecache/298/libch.so
17. ? @ 0x0000000011643953 in /data5/hadoop/yarn/local/usercache/zhangzhibiao/filecache/298/libch.so
18. ? @ 0x000000001163b6f0 in /data5/hadoop/yarn/local/usercache/zhangzhibiao/filecache/298/libch.so
19. ? @ 0x000000001163b049 in /data5/hadoop/yarn/local/usercache/zhangzhibiao/filecache/298/libch.so
20. ? @ 0x0000000011648088 in /data5/hadoop/yarn/local/usercache/zhangzhibiao/filecache/298/libch.so
21. ? @ 0x0000000011648270 in /data5/hadoop/yarn/local/usercache/zhangzhibiao/filecache/298/libch.so
22. ? @ 0x000000000c0e16d0 in /data5/hadoop/yarn/local/usercache/zhangzhibiao/filecache/298/libch.so
23. ? @ 0x000000000714ae77 in /data5/hadoop/yarn/local/usercache/zhangzhibiao/filecache/298/libch.so

	at io.glutenproject.vectorized.BatchIterator.nativeHasNext(Native Method)
	at io.glutenproject.vectorized.BatchIterator.hasNextInternal(BatchIterator.java:53)
	at io.glutenproject.vectorized.GeneralOutIterator.hasNext(GeneralOutIterator.java:32)
	at io.glutenproject.backendsapi.clickhouse.CHIteratorApi$$anon$1.hasNext(CHIteratorApi.scala:137)
	at io.glutenproject.vectorized.CloseableCHColumnBatchIterator.$anonfun$hasNext$1(CloseableCHColumnBatchIterator.scala:42)
	at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:23)
	at io.glutenproject.metrics.GlutenTimeMetric$.withNanoTime(GlutenTimeMetric.scala:41)
	at io.glutenproject.vectorized.CloseableCHColumnBatchIterator.hasNext(CloseableCHColumnBatchIterator.scala:42)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at org.apache.spark.shuffle.CelebornHashBasedCHColumnarShuffleWriter.internalWrite(CelebornHashBasedCHColumnarShuffleWriter.scala:92)
	at org.apache.spark.shuffle.CelebornHashBasedCHColumnarShuffleWriter.write(CelebornHashBasedCHColumnarShuffleWriter.scala:87)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:60)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:136)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1504)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
23/09/13 17:27:55.585 INFO [dispatcher-Executor] YarnCoarseGrainedExecutorBackend: Got assigned task 49
```

### Spark version

Spark-3.3.x

**Comment by taiyang-li** [comment] 2023-09-21 03:21
Can't reproduce it if building Kyligence/Clickhouse with patch from: https://github.com/ClickHouse/ClickHouse/pull/54664 
Let's wait for it to be merged.

**Closed** 2023-10-13 04:04 UTC
Labels: bug, triage
