### ISSUE TITLE
Shim error when running with EMR Spark 3.3.0-amzn-0

### ISSUE THREAD

**Issue by theosib-amazon** [oap-project/gluten#642] opened 2022-11-30 19:03 UTC
I'm trying to get Gluten (built for Spark 3.3.0) to work with EMR Spark (3.3.0-amzn-0). I'm getting this error:

```
22/11/30 18:58:17 INFO SparkShimLoader: Loading Spark Shims for version: 3.3.0
Exception in thread "main" java.lang.IllegalStateException: No Spark Shim Provider found for 3.3.0
        at io.glutenproject.sql.shims.SparkShimLoader$.loadSparkShimProvider(SparkShimLoader.scala:61)
        at io.glutenproject.sql.shims.SparkShimLoader$.getSparkShimProvider(SparkShimLoader.scala:76)
        at io.glutenproject.sql.shims.SparkShimLoader$.getSparkShims(SparkShimLoader.scala:32)
        at io.glutenproject.extension.TransformPreOverrides.replaceWithTransformerPlan(ColumnarOverrides.scala:191)
        at io.glutenproject.extension.TransformPreOverrides.apply(ColumnarOverrides.scala:326)
```

**Comment by theosib-amazon** [comment] 2022-11-30 20:09
I noticed that the pom.xml file actually says that the spark33 version is 3.3.1, so I made these changes:

```
-    <spark33.version>3.3.1</spark33.version>
+    <spark33.version>3.3.0</spark33.version>
```

```
-  val DESCRIPTOR = SparkShimDescriptor(3, 3, 1)
+  val DESCRIPTOR = SparkShimDescriptor(3, 3, 0)
```

That got rid of the shim problem, but now I have this error when trying to run a query:

```
Exception in thread "main" java.lang.AbstractMethodError: Method org/apache/spark/sql/execution/ColumnarSubqueryBroadcastExec.materialize()Lscala/concu
rrent/Future; is abstract
        at org.apache.spark.sql.execution.ColumnarSubqueryBroadcastExec.materialize(ColumnarSubqueryBroadcastExec.scala)
        at org.apache.spark.sql.execution.ReusedSubqueryExec.materialize(basicPhysicalOperators.scala:1047)
        at org.apache.spark.sql.execution.adaptive.MaterializeExecutable.tryStart(AdaptiveExecutable.scala:368)
        at org.apache.spark.sql.execution.adaptive.AdaptiveExecutorRuntime.startChild(AdaptiveExecutor.scala:232)
```

**Comment by theosib-amazon** [comment] 2022-11-30 20:16
It's peculiar that the error here is the same as for https://github.com/oap-project/gluten/issues/633. I'm going to change the hadoop version back to 3.2.2 and see what happens.

**Comment by theosib-amazon** [comment] 2022-11-30 20:34
No. Changing the hadoop version back to 3.2.2 didn't fix the problem.

**Comment by theosib-amazon** [comment] 2022-11-30 20:47
Could this be related to protobuf, arrow, or flatbuffers in any way? With OSS Spark, I had to remove those jars so that the gluten jar can override them. Has this changed?

**Comment by FelixYBW** [comment] 2022-12-01 03:44
@theosib-amazon 
No, it's not related to those jars. In TPCH/DS tests, those jars are not used.
The root cause is the API conflict of Gluten and AWS EMR spark. EMR spark optimized the vanilla Spark and changes some APIs which gluten is using. So you need to modify Gluten to adapt EMR spark's API. We can't modify it without EMR's source code.

**Comment by theosib-amazon** [comment] 2022-12-01 13:36
Yes. We just figured this out last evening. This is definitely the results of some optimizations made by the EMR team. Thank you!

**Comment by FelixYBW** [comment] 2022-12-03 09:06
let's close this one since it's not Gluten bug

**Closed by FelixYBW** 2022-12-03 09:06 UTC
Labels: bug
