### ISSUE TITLE
Can't decide data type of null value in gluten test framework, when transforming InteralRow to DataFrame

### ISSUE THREAD

**Issue by taiyang-li** [oap-project/gluten#601] opened 2022-11-23 06:51 UTC
**Describe the bug**
Can't decide data type of null value in gluten test framework, when transforming InteralRow to DataFrame.

```
def convertInternalRowToDataFrame(inputRow: InternalRow): DataFrame = {
    val structFileSeq = new ArrayBuffer[StructField]()
    val values = inputRow match {
      case genericInternalRow: GenericInternalRow =>
        genericInternalRow.values
      case _ => throw new UnsupportedOperationException("Unsupported InternalRow.")
    }
    val inputValues = values.map {
      _ match {
        case boolean: java.lang.Boolean =>
          structFileSeq.append(StructField("bool", BooleanType, boolean == null))
        case short: java.lang.Short =>
          structFileSeq.append(StructField("i16", ShortType, short == null))
        case byte: java.lang.Byte =>
          structFileSeq.append(StructField("i8", ByteType, byte == null))
        case integer: java.lang.Integer =>
          structFileSeq.append(StructField("i32", IntegerType, integer == null))
        case long: java.lang.Long =>
          structFileSeq.append(StructField("i64", LongType, long == null))
        case float: java.lang.Float =>
          structFileSeq.append(StructField("fp32", FloatType, float == null))
        case double: java.lang.Double =>
          structFileSeq.append(StructField("fp64", DoubleType, double == null))
        case utf8String: UTF8String =>
          structFileSeq.append(StructField("str", StringType, utf8String == null))
        case byteArr: Array[Byte] =>
          structFileSeq.append(StructField("vbin", BinaryType, byteArr == null))
        case decimal: Decimal =>
          structFileSeq.append(StructField("dec",
            DecimalType(decimal.precision, decimal.scale), decimal == null))
        case _ =>
          /// Notice: null value maybe not integer type, because we can't decide its type only from InteralRow.
          structFileSeq.append(StructField("n", IntegerType, true))
      }
    }
    _spark.internalCreateDataFrame(_spark.sparkContext.parallelize(Seq(inputRow)),
      StructType(structFileSeq))
  }
```

**To Reproduce**
I reproduces when running test case named "case when" in gluten-ut/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenConditionalExpressionSuite.scala

**Expected behavior**

**Additional context**

**Comment by FelixYBW** [comment] 2022-11-28 07:39
@JkSelf did you see the issue when you pass the GlutenConditionalExpressionSuite?

**Comment by JkSelf** [comment] 2022-11-28 07:47
@FelixYBW I haven't started enable `GlutenConditionalExpressionSuite` yet. And I will take a look this issue later.

**Comment by JkSelf** [comment] 2022-11-30 10:59
@taiyang-li @FelixYBW 
I enabled GlutenConditionalExpressionSuite in gluten in [PR#631](https://github.com/oap-project/gluten/pull/631). It passed the uts both CH and velox backend. And I cannot reproduce this issue now. It maybe fixed by other commits.

**Comment by FelixYBW** [comment] 2022-12-01 04:05
@taiyang-li can you try with latest branch?

**Comment by jinchengchenghh** [comment] 2023-01-18 07:57
Can this issue be closed? @taiyang-li

**Closed** 2023-01-18 12:15 UTC
Labels: bug
