### ISSUE TITLE
Shim error when running with EMR Spark 3.2.1-amzn-0

### ISSUE THREAD

**Issue by theosib-amazon** [oap-project/gluten#633] opened 2022-11-29 21:25 UTC
I'm trying to get Gluten to work with EMR Spark, and as far as I can tell, the closest 3.2.x version I can get for EMR Spark is "3.2.1-amzn-0". Even if there is 3.2.2 support I don't know about, it took me two days to install all the system libraries to get Gluten's native code to link on Amazon Linux 2.

The error I got the first time was this:
```
22/11/29 18:33:12 INFO SparkShimLoader: Loading Spark Shims for version: 3.2.1
Exception in thread "main" java.lang.IllegalStateException: No Spark Shim Provider found for 3.2.1
        at io.glutenproject.sql.shims.SparkShimLoader$.loadSparkShimProvider(SparkShimLoader.scala:61)
        at io.glutenproject.sql.shims.SparkShimLoader$.getSparkShimProvider(SparkShimLoader.scala:76)
        at io.glutenproject.sql.shims.SparkShimLoader$.getSparkShims(SparkShimLoader.scala:32)
```

So I changed the version numbers in the main pom.xml file like this:

```
   <properties>
-    <spark32.version>3.2.2</spark32.version>
+    <spark32.version>3.2.1</spark32.version>
     <spark32.scala>2.12.15</spark32.scala>
     <spark32bundle.version>3.2</spark32bundle.version>
     <spark33.version>3.3.1</spark33.version>
@@ -115,7 +115,7 @@
     <build-helper-maven-plugin.version>3.2.0</build-helper-maven-plugin.version>
     <scala.compiler.version>4.3.0</scala.compiler.version>
     <maven.compiler.plugin>3.8.0</maven.compiler.plugin>
-    <maven.jar.plugin>3.2.2</maven.jar.plugin>
+    <maven.jar.plugin>3.2.1</maven.jar.plugin>
     <scalastyle.version>1.0.0</scalastyle.version>
     <scalatest-maven-plugin.version>2.2.0</scalatest-maven-plugin.version>
   </properties>
@@ -171,13 +171,13 @@
     <profile>
       <id>dataproc-2.0</id>
       <properties>
-        <hadoop.version>3.2.2</hadoop.version>
+        <hadoop.version>3.2.1</hadoop.version>
       </properties>
     </profile>
     <profile>
       <id>emr-6.3.0</id>
       <properties>
-        <hadoop.version>3.2.2</hadoop.version>
+        <hadoop.version>3.2.1</hadoop.version>
       </properties>
     </profile>
```

This lead to a failure of the Spark32ShimsSuite test, so I disabled all tests, and now I get this error:

```
[INFO] Compiling 276 source files to /local/home/theosib/gluten.latest/gluten/gluten-core/target/scala-2.12/classes at 1669751375256
[ERROR] /local/home/theosib/gluten.latest/gluten/gluten-core/src/main/scala/io/glutenproject/extension/columnar/TransformHintRule.scala:82: error: wrong number of 
arguments for pattern org.apache.spark.sql.execution.aggregate.HashAggregateExec(requiredChildDistributionExpressions: Option[Seq[org.apache.spark.sql.catalyst.expressions.Expression]],groupingExpressions: Seq[org.apache.spark.sql.catalyst.expressions.NamedExpression],aggregateExpressions: Seq[org.apache.spark.sql.catalyst.e
xpressions.aggregate.AggregateExpression],aggregateAttributes: Seq[org.apache.spark.sql.catalyst.expressions.Attribute],initialInputBufferOffset: Int,resultExpress
ions: Seq[org.apache.spark.sql.catalyst.expressions.NamedExpression],child: org.apache.spark.sql.execution.SparkPlan)
[ERROR]     case agg @ HashAggregateExec(_, _, _, _, _, _, _, _, child: ExpandExec) =>
[ERROR]                                 ^
[WARNING] /local/home/theosib/gluten.latest/gluten/gluten-core/src/main/scala/org/apache/spark/shuffle/sort/ColumnarShuffleManager.scala:133: warning: abstract typ
e K in type org.apache.spark.shuffle.sort.ColumnarShuffleHandle[K, _] is unchecked since it is eliminated by erasure
[WARNING]     if (handle.isInstanceOf[ColumnarShuffleHandle[K, _]]) {
[WARNING]                            ^
[WARNING] one warning found
[ERROR] one error found
```

I don't really know what's going on in that code, but if you could provide me any tips on how to work around it, that would be great.

Thanks!

**Comment by theosib-amazon** [comment] 2022-11-29 21:30
EMR Spark versions skip from `Spark: Spark 3.2.1 on Hadoop 3.2.1 YARN with and Zeppelin 0.10.0` to `Spark: Spark 3.3.0 on Hadoop 3.2.1 YARN with and Zeppelin 0.10.1`. So if your 3.3.x support is for 3.3.0, I could make a new cluster, but I really don't look forward to doing all that manual setup again.

**Comment by jinchengchenghh** [comment] 2022-11-30 02:57
I have a commit to help support compile spark321, but it cannot pass all the unit test, you can try it https://github.com/jinchengchenghh/gluten/commit/96ecd54704350effa12560d50503fd2bb012d28f

**Comment by theosib-amazon** [comment] 2022-11-30 16:04
Thanks for your help! I got those code changes in, and I no longer get the shim error. However, I get a new one:

```
Exception in thread "main" java.lang.AbstractMethodError: Method org/apache/spark/sql/execution/ColumnarSubqueryBroadcastExec.materialize()Lscala/concurre
nt/Future; is abstract
        at org.apache.spark.sql.execution.ColumnarSubqueryBroadcastExec.materialize(ColumnarSubqueryBroadcastExec.scala)
        at org.apache.spark.sql.execution.ReusedSubqueryExec.materialize(basicPhysicalOperators.scala:1038)
        at org.apache.spark.sql.execution.adaptive.MaterializeExecutable.tryStart(AdaptiveExecutable.scala:368)
        at org.apache.spark.sql.execution.adaptive.AdaptiveExecutorRuntime.startChild(AdaptiveExecutor.scala:232)
```

**Comment by theosib-amazon** [comment] 2022-11-30 16:07
Seems like ColumnarSubqueryBroadcastExec is supposed to have a materialize() method, but it doesn't have one.

**Comment by jinchengchenghh** [comment] 2022-12-01 02:23
What's your spark version? It seems the end line is 902 in spark3.2.1 release version. https://github.com/apache/spark/blob/v3.2.1/sql/core/src/main/scala/org/apache/spark/sql/execution/basicPhysicalOperators.scala#L902
But the error line is following in your case
```
at org.apache.spark.sql.execution.ReusedSubqueryExec.materialize(basicPhysicalOperators.scala:1038)
```

**Comment by FelixYBW** [comment] 2022-12-01 03:42
@theosib-amazon the root cause is the API conflict of Gluten and AWS EMR spark. EMR spark optimized the vanilla Spark and changes some APIs which gluten is using. So you need to modify Gluten to adapt EMR spark's API. We can't modify it without EMR's source code.

**Comment by theosib-amazon** [comment] 2022-12-01 13:36
Yes. We just figured this out last evening. This is definitely the results of some optimizations made by the EMR team.

**Comment by FelixYBW** [comment] 2022-12-03 09:06
let's close this one since it's not Gluten bug

**Closed by FelixYBW** 2022-12-03 09:06 UTC
Labels: bug
